In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [3]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [4]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [5]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                    [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [6]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [7]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [8]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [9]:
data[4] = np.nan

In [10]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [11]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data = pd.DataFrame(np.random.standard_normal((7, 3)))

In [13]:
data.iloc[:4, 1] = np.nan

In [14]:
data.iloc[:2, 2] = np.nan

In [15]:
data

0         1         2
0  1.252139       NaN       NaN
1 -1.046330       NaN       NaN
2  1.259782       NaN -0.508818
3 -1.143783       NaN -0.385248
4  0.808280 -2.274171 -0.240573
5 -0.484449 -0.332146 -0.660954
6  0.035385 -2.155605 -0.318514

In [16]:
data.dropna()

0         1         2
4  0.808280 -2.274171 -0.240573
5 -0.484449 -0.332146 -0.660954
6  0.035385 -2.155605 -0.318514

In [17]:
data.dropna(thresh=2)

0         1         2
2  1.259782       NaN -0.508818
3 -1.143783       NaN -0.385248
4  0.808280 -2.274171 -0.240573
5 -0.484449 -0.332146 -0.660954
6  0.035385 -2.155605 -0.318514

In [18]:
data.fillna(0)

0         1         2
0  1.252139  0.000000  0.000000
1 -1.046330  0.000000  0.000000
2  1.259782  0.000000 -0.508818
3 -1.143783  0.000000 -0.385248
4  0.808280 -2.274171 -0.240573
5 -0.484449 -0.332146 -0.660954
6  0.035385 -2.155605 -0.318514

In [19]:
data.fillna({1: 0.5, 2: 0})

0         1         2
0  1.252139  0.500000  0.000000
1 -1.046330  0.500000  0.000000
2  1.259782  0.500000 -0.508818
3 -1.143783  0.500000 -0.385248
4  0.808280 -2.274171 -0.240573
5 -0.484449 -0.332146 -0.660954
6  0.035385 -2.155605 -0.318514

In [20]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [21]:
df.iloc[2:, 1] = np.nan

In [22]:
df.iloc[4:, 2] = np.nan

In [23]:
df

0         1         2
0 -1.807955  0.509420  0.660408
1 -1.377537  0.890891  2.212511
2 -0.635314       NaN -0.566128
3 -0.049371       NaN -0.438833
4 -0.725388       NaN       NaN
5  1.113982       NaN       NaN

In [24]:
df.fillna(method="ffill")

/tmp/ipykernel_7247/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0 -1.807955  0.509420  0.660408
1 -1.377537  0.890891  2.212511
2 -0.635314  0.890891 -0.566128
3 -0.049371  0.890891 -0.438833
4 -0.725388  0.890891 -0.438833
5  1.113982  0.890891 -0.438833

In [25]:
df.fillna(method="ffill", limit=2)

/tmp/ipykernel_7247/1627181726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)


0         1         2
0 -1.807955  0.509420  0.660408
1 -1.377537  0.890891  2.212511
2 -0.635314  0.890891 -0.566128
3 -0.049371  0.890891 -0.438833
4 -0.725388       NaN -0.438833
5  1.113982       NaN -0.438833

In [26]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [27]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [28]:
data = pd.DataFrame[{"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]}]

TypeError: type 'DataFrame' is not subscriptable

In [29]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                    "k2": [1, 1, 2, 3, 3, 4, 4]})

In [30]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [31]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [32]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [33]:
data["v1"] = range(7)

In [34]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [35]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [36]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [37]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                             "pastrami", "corned beef", "bacon",
                             "pastrami", "honey ham", "nova lox"],
                    "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [38]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [39]:
meat_to_animal = {"bacon": "pig",
                 "pulled pork": "pig",
                 "pastrami": "cow",
                 "corned beef": "cow",
                 "honey ham": "pig",
                 "nova lox": "salmon"
                 }

In [40]:
data["animal"] = data["food"].map(meat_to_animal)

In [41]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [42]:
def get_animal(x):
    return meat_to_animal[x]

In [43]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [44]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [45]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [46]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [47]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [48]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [49]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [50]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                   index=["Ohio", "Colorado", "New York"],
                   columns=["one", "two", "three", "four"])

In [51]:
def transform(x):
    return x[:4].upper()

In [52]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [53]:
data.index = data.index.map(transform)

In [54]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [55]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [56]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [57]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [58]:
bins = [18, 25, 35, 60, 100]

In [59]:
age_categories = pd.cut(ages, bins)

In [60]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [61]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [62]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [63]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [64]:
pd.value_counts(age_categories)

/tmp/ipykernel_7247/3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [65]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [66]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [67]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [68]:
data = np.random.uniform(size=20)

In [69]:
pd.cut(data, 4, precision=2)

[(0.29, 0.52], (0.29, 0.52], (0.055, 0.29], (0.75, 0.98], (0.29, 0.52], ..., (0.29, 0.52], (0.055, 0.29], (0.055, 0.29], (0.52, 0.75], (0.055, 0.29]]
Length: 20
Categories (4, interval[float64, right]): [(0.055, 0.29] < (0.29, 0.52] < (0.52, 0.75] < (0.75, 0.98]]

In [70]:
data = np.random.standard_normal(1000)

In [71]:
quartiles = pd.ocut(data, 4, precision=2)

AttributeError: module 'pandas' has no attribute 'ocut'

In [72]:
quartiles = pd.qcut(data, 4, precision=2)

In [73]:
quartiles

[(-3.1999999999999997, -0.63], (0.66, 3.65], (-3.1999999999999997, -0.63], (0.66, 3.65], (-3.1999999999999997, -0.63], ..., (-3.1999999999999997, -0.63], (0.0024, 0.66], (0.0024, 0.66], (0.66, 3.65], (0.66, 3.65]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.1999999999999997, -0.63] < (-0.63, 0.0024] < (0.0024, 0.66] < (0.66, 3.65]]

In [74]:
pd.value_counts(quartiles)

/tmp/ipykernel_7247/3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-3.1999999999999997, -0.63]    250
(-0.63, 0.0024]                 250
(0.0024, 0.66]                  250
(0.66, 3.65]                    250
Name: count, dtype: int64

In [75]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.187, -1.175]    100
(-1.175, 0.0024]    400
(0.0024, 1.29]      400
(1.29, 3.65]        100
Name: count, dtype: int64

In [76]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [77]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021365    -0.028242     0.031360     0.028629
std       0.964834     0.966296     0.960341     1.006762
min      -3.023272    -3.548271    -3.480284    -3.114319
25%      -0.600347    -0.705262    -0.594703    -0.655060
50%       0.001481    -0.006324     0.043146     0.025852
75%       0.670948     0.606113     0.676329     0.727099
max       2.939132     3.518189     2.995885     2.805486

In [78]:
col = data[2]

In [79]:
col[col.abs() > 3]

140   -3.365503
673   -3.480284
786   -3.013254
Name: 2, dtype: float64

In [80]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
1    0.049060  0.548549  1.439110 -3.114319
90  -0.058007 -0.690460  0.653787 -3.106619
140 -0.970988  0.724392 -3.365503 -0.000861
360 -0.760559  3.246165  0.473871 -0.440693
374  1.200174  1.097909  0.030135 -3.002241
422  0.094364 -0.574201 -0.414333 -3.020824
459  1.630513 -3.548271  0.670127 -0.044889
515 -1.077095 -3.114598  1.199213 -0.461066
673 -0.252416  1.043529 -3.480284  0.074706
712  0.962959 -3.100790  0.525742  1.676563
713  0.535111  3.518189 -0.961905  0.210637
786  0.822671 -0.306022 -3.013254 -1.025020
812 -3.023272  0.548656  0.476487 -0.267586

In [81]:
data[data.abs() > 3] = np.sign(data) * 3

In [82]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021388    -0.028243     0.032219     0.028873
std       0.964761     0.961195     0.957432     1.006014
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.600347    -0.705262    -0.594703    -0.655060
50%       0.001481    -0.006324     0.043146     0.025852
75%       0.670948     0.606113     0.676329     0.727099
max       2.939132     3.000000     2.995885     2.805486

In [83]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1  1.0  1.0  1.0 -1.0
2  1.0  1.0 -1.0 -1.0
3 -1.0  1.0  1.0 -1.0
4 -1.0 -1.0  1.0  1.0

In [84]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [85]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [86]:
sampler = np.random.permutation(5)

In [87]:
sampler

array([0, 1, 4, 2, 3])

In [88]:
df.take(sampler)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27

In [89]:
df.iloc[sampler]

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27

In [90]:
column_sampler = np.random.permutation(7)

In [91]:
column_sampler

array([1, 2, 3, 5, 0, 6, 4])

In [92]:
df.take(column_sampler, axis="columns")

1   2   3   5   0   6   4
0   1   2   3   5   0   6   4
1   8   9  10  12   7  13  11
2  15  16  17  19  14  20  18
3  22  23  24  26  21  27  25
4  29  30  31  33  28  34  32

In [93]:
df.sample(n=3)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34

In [94]:
choices = pd.Series([5, 7, -1, 6, 4])

In [95]:
choices.sample(n=10, replace=True)

3    6
0    5
2   -1
3    6
2   -1
2   -1
1    7
0    5
2   -1
0    5
dtype: int64

In [96]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                  "data1": range(6)})

In [97]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [98]:
pd.get_dummies(df["key"])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [99]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [100]:
df_with_dummy = df[["data1"]].join(dummies)

In [101]:
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False